### ISSUE TITLE
"Deep Dive into Crypto “Exceptional Access” Mandates: Effective or Constitutional—Pick One" has wrong author "and"

### ISSUE THREAD

**Issue by dkg** [The-Encryption-Compendium/TECv2#28]
"Deep Dive into Crypto “Exceptional Access” Mandates: Effective or Constitutional—Pick One" has the wrong author on encryptioncompendium.org.  it does *not* have the wrong author on the-encryption-compendium.github.io, though.

in the former site, the author is listed as "and".  in the github.io site, it shows up as "Cardozo, Nate and Crocker, Andrew"

https://encryptioncompendium.org/entries/deep-dive-into-crypto-exceptional-access-mandates-a6e2187d/
https://the-encryption-compendium.github.io/entries/29/

**Comment by kernelmethod** [comment]
Just pushed an update to the official site, this should now be fixed: https://encryptioncompendium.org/entries/deep-dive-into-crypto-exceptional-access-mandates-685e068d/
