### ISSUE TITLE
Add issue templates

### ISSUE THREAD

**Issue by kernelmethod** [The-Encryption-Compendium/TECv2#3]
As in the TECv1 repository, there should be at least two issue templates: one for bug reports, and a second for feature requests.

**Comment by dkg** [comment]
there appear to be two issue templates already here: one for a bug report, another for an issue report in a compendium entry.

so maybe this can be closed?

**Comment by kernelmethod** [comment]
Yes, I think this one and a few of the other early issues I put in here can be closed, since they've either been resolved or aren't really relevant anymore.
