### ISSUE TITLE
"Encryption is a Human Rights issue" has mojibake in it

### ISSUE THREAD

**Issue by dkg** [The-Encryption-Compendium/TECv2#31]
"Encryption is a Human Rights issue: Your Privacy and Pree Speech Depend on It" contains in its abstract:

> Encryption was at the heart of the ideas that led to the Americaâ€™s founding

I'm pretty sure that's meant to be something like "Encryption was at the heart of the ideas that led to the America's founding", but it's been mangled by character encoding issues (i.e., [mojibake](https://en.wikipedia.org/wiki/Mojibake)).  Not sure whether there are others like it in the dataset.

https://encryptioncompendium.org/entries/encryption-is-a-human-rights-issue-your-privacy-an-468af322/
https://the-encryption-compendium.github.io/entries/146/

**Comment by kernelmethod** [comment]
Good catch. I've just fixed it in Zotero and confirmed the fix locally; I'll close this issue once it's been propagated to the site.

**Comment by kernelmethod** [comment]
Should now be fixed alongside #28: https://encryptioncompendium.org/entries/encryption-is-a-human-rights-issue-your-privacy-an-454a81ce/
