### ISSUE TITLE
rename default branch from `master` to `main`

### ISSUE THREAD

**Issue by dkg** [The-Encryption-Compendium/TECv2#41]
Modern git repos use `main` as the name of the default branch, not `master`.  there are [sensible and friendly reasons](https://www.ietf.org/archive/id/draft-knodel-terminology-06.html#name-master-slave) for this change, but even if you don't believe in doing it for those reasons, people starting out on git today will be confused by the repo having a non-default name.

I recommend changing the name of the default branch to `main`, and updating anywhere in the CI/build/"protected branches" to reflect that change.  If you run into any trouble doing the rename, i'd be happy to help you figure out the problem.

**Comment by kernelmethod** [comment]
Done! Thanks for flagging that.

**Comment by dkg** [comment]
thanks for the prompt cleanup, @kernelmethod!  always better to rip the scab off in one piece :)
